version: '3.7'

services:
  server:
    image: jenkins:1.0
    volumes:
      - home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 8080
        published: 8080

volumes:
  home:
