version: '3.7'

services:
  server:
    image: ${REGISTRY}jenkins:$VERSION
    volumes:
      - data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - published: $PORT
        target: 8080

volumes:
  data:
